### ISSUE TITLE
Implement initial audiocraft-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/audiocraft-container#1]
## Summary

Implement a Docker container to run AudioCraft models.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install AudioCraft and dependencies
- [ ] Copy AudioCraft code
- [ ] Create entrypoint script
  - Import AudioCraft and start Python shell  
- [ ] Include base AudioCraft models
  - MusicGen
  - AudioGen
  - EnCodec
- [ ] Create data volume
  - For caching downloaded models
- [ ] Write README
  - Overview
  - Usage
  - Models
  - Volumes
  
## Requirements  

- Dockerfile builds image with AudioCraft installed
- Entrypoint launches Python shell with AudioCraft imported
- Base AudioCraft models included
- Data volume for caching models
- README explains usage and configuration

## Resources

- AudioCraft repo: https://github.com/facebookresearch/audiocraft
